Fix invalid filehandle read
Borewit/strtok3 pull request #1141
Opened 2024-08-06 17:36 UTC by Araxeus

NodeJS handles `filehandle.read()` with length 0 gracefully (while its an error)

Bun (https://github.com/oven-sh/bun) -  [doesn't handle it](https://github.com/user-attachments/assets/e50ff126-4ffb-4bc7-ad2b-9666ffbea68d) right now, could be argued if a library should support bun specifically but this is a harmless fix that only prevents invalid filehandle read

2024-08-06 21:26 UTC, Borewit commented
I think the title of this issue is slightly confusing. A [file handle or file descriptor](https://en.wikipedia.org/wiki/File_descriptor) is the number referring to an pen file. An _invalid file handle_, I read as a number which actually does not refer to an open file at all.

2024-08-06 21:29 UTC, Araxeus commented
I can rename the PR to whatever you like

I originally named it this way because thats the name of the function that throws with length 0
https://github.com/Borewit/strtok3/blob/3b8a97473cfd96b863379322f035fae5958775c1/lib/FileTokenizer.ts#L22

2024-08-07 07:33 UTC, Borewit requested changes
I have a few concerns:

- I think all tokenizers should be consistent in the way they handle 0 byte read request
- Should a 0 byte read be tolerated, as this could easily lead to an infinite loop

2024-08-07 07:33 UTC, Borewit commented on lib/FileTokenizer.ts
> +    if (!normOptions.length) return 0;
```suggestion
    if (normOptions.length === 0) return 0;
```

2024-08-07 07:52 UTC, Araxeus commented
> I think all tokenizers should be consistent in the way they handle 0 byte read request

Nothing changed really - that was already the default way that nodejs handled length 0

But if you want you can obviously make follow up PR's to adjust the other tokenizers

> Should a 0 byte read be tolerated, as this could easily lead to an infinite loop

It was allowed until now, so forbidding it would be a regression

2024-08-07 08:10 UTC, Borewit commented
| It was allowed until now, so forbidding it would be a regression (and could break popular packages that depends on this like file-type)

I agree, and just verified it, all tokizenizers consistently tolerate a 0 byte read.

| NodeJS handles filehandle.read() with length 0 gracefully (while its an error)

Why is that?

I am not familiar with [Bun](https://github.com/oven-sh/bun), but I see that they claim and aim for Node.js-compatibility.

So this PR actually a workaround to overcome a Node.js incompatibility in Bum?
Should this not be an issue raised at Bum?

2024-08-07 10:32 UTC, Araxeus commented
> | NodeJS handles filehandle.read() with length 0 gracefully (while its an error)
> 
>> Why is that?

I dont know why they allow it

> I am not familiar with [Bun](https://github.com/oven-sh/bun), b> So this PR actually a workaround to overcome a Node.js incompatibility in Bum?
> Should this not be an issue raised at Bum?


Kinda, but its not really an issue right? Length 0 doesnt make sense, its more of an issue with NodeJS that allows it in the first place
 
And like i said above,  this is really a harmless fix for a situation that shouldn't happen in the first place, I personally don't see a reason **not** to merge

2024-08-07 12:35 UTC, Borewit commented
> > | NodeJS handles filehandle.read() with length 0 gracefully (while its an error)
> > > Why is that?
> 
> I dont know why they allow it

What I meant, why do you claim is is an error?

> 
> > I am not familiar with [Bun](https://github.com/oven-sh/bun), b> So this PR actually a workaround to overcome a Node.js incompatibility in Bum?
> > Should this not be an issue raised at Bum?
> 
> Kinda, but its not really an issue right? Length 0 doesnt make sense, its more of an issue with NodeJS that allows it in the first place

No it is not an issue with Nodejs, unless they claim to throw this error on a 0 byte request. 

As far as I can see it does what is says, you ask to read 0 bytes, you get 0 bytes. We can come up with some arguments to do this different, but that does not make the current implementation invalid.

> 
> And like i said above, this is really a harmless fix for a situation that shouldn't happen in the first place, I personally don't see a reason **not** to merge, but it's ultimately your choice of course

I have no problem to merge this, but:

1.  I like (preferably you) to be clear on why this done. It is a **workaround for an issue [Bun](https://github.com/oven-sh/bun)**, which throws an error on a 0 byte length `filehandle.read()`. 
2. You should raise the issue at [Bun](https://github.com/oven-sh/bun). Please provide reference to that issue here.

> 
> Also returning 0 for a read with length 0 seems like good logic to avoid unnecessary function calls

Indeed. It has certain advantages as well. Maybe that is why they did not chose to raise an error.

2024-08-07 12:51 UTC, Araxeus commented
> I like (preferably you) to be clear on why this done. It is a workaround for an issue Bun, which throws an error on a 0 byte length filehandle.read().

I did write the reason in the PR description :)

I opened the PR because of an issue with Bun, but also because I think the behavior that this PR introduces makes sense (I dont just open PR's in any library that bun doesnt handle)

2024-08-07 13:04 UTC, Borewit commented
| I did write the reason in the PR description :)

Now it does it indeed.

2024-08-07 14:11 UTC, Araxeus commented
I opened an issue on Bun's repo https://github.com/oven-sh/bun/issues/13146 and applied your suggested fix.

Sorry for not being explicit enough about the reasoning for the PR

2024-08-07 15:55 UTC, Borewit commented
Is there is anything preventing you to raise the actual issue at Bun?

2024-08-07 16:05 UTC, Araxeus commented
I don't understand, what do you mean? I've literally just linked the issue? what do you mean "the actual issue"?

2024-08-07 16:36 UTC, Borewit commented
> I don't understand, what do you mean? I've literally just linked the issue and you liked the comment? what do you mean "the actual issue"?

Catch some fresh air buddy, at the time I wrote that comment, that link was not present. 

Thanks for taking the effort to identify and address this issue.   

In you initial description you expressed being surprised on a package with a download rate 20 million/week. Based on on that same assumption, no one takes action. There must be some smarter dude who fixes the issue.

2024-08-07 16:36 UTC, merged

2024-08-07 16:44 UTC, Borewit commented
Part of [v8.0.2](https://github.com/Borewit/strtok3/releases/tag/v8.0.2)